# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "capybara", "3.10.0"
gem "rspec", "3.8.0"
gem "selenium-webdriver", "3.14.0"
