# frozen_string_literal: true

source "https://rubygems.org"

#gem "capybara","3.31.0"
#gem "rspec","3.9.0"
#gem "selenium-webdriver","3.142.7"
#gem "ffi","1.12.2"

gem "capybara", "3.10.0"
gem "rspec", "3.8.0"
gem "selenium-webdriver", "3.14.0"